on:
  workflow_call:
    inputs:
      block_endpoint:
        description: This endpoint should respond status 200 for the pre-release to continue.
        required: false
        type: string
        default: https://newrelic.github.io/newrelic-coreint-automation/automatic_release_enable


jobs:
  unblock:
    name: Check Release status
    runs-on: ubuntu-latest
    steps:

