name: test is held

on:
  workflow_dispatch:
    inputs:
      block_endpoint:
        description: 'endpoint'
        required: true
        default: 'test'
        type: string

jobs:
  check-block-endpoint:
    uses: ./.github/workflows/status.yaml
    with:
      block_endpoint: ${{ inputs.block_endpoint }}
