name: test is held

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'endpoint'
        required: true
        default: 'test'
        type: string

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: exit 0

  test-reusable:
    name: test reusable
    uses: ./.github/workflows/reusable.yaml
    with:
      lock_endpoint: ${{ inputs.endpoint }}
