on:
  workflow_call:
    inputs:
      block_endpoint:
        description: This endpoint should respond status 200 for the pre-release to continue.
        required: false
        type: string
        default: https://newrelic.github.io/newrelic-coreint-automation/automatic_release_enable

jobs:
  status:
    name: Check release block
    runs-on: ubuntu-latest
    steps:
      - name: Check block endpoint
        run: |
          http_status=$(curl -s -o /dev/null -w "%{http_code}" "${{ inputs.block_endpoint }}")

          if [ "$http_status" != 200 ]; then
            echo "Fail checking release block endpoint: ${{ inputs.block_endpoint }}"
            exit 1
          fi
